# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Elixir CI
on: push

jobs:
  Escript-Build:
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: ./yafia
    name: OTP ${{matrix.otp}} / Elixir ${{matrix.elixir}}
    strategy:
      matrix:
        otp: ["26.0"]
        elixir: ["1.16.2"]
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}
      - run: mix deps.get
      #  - run: mix test
      - run: mix escript.build
